// src/components/footer.jsx
import React from 'react';

const Footer = () => (
  <footer>
    <div className="container">
      <div className="row">
        <div className="col-md-6">
          <div className="footer-section">
            <h5>Connect</h5>
            <div className="row">
              <div className="col-md-12">
                <a href="http://facebook.com" className="social-media-icon">
                  <img alt="" className="icon" src="assets/img/facebook.svg" />
                </a>
                <a href="http://twitter.com" className="social-media-icon">
                  <img alt="" className="icon" src="assets/img/twitter.svg" />
                </a>
                <a href="http://linkedin.com" className="social-media-icon">
                  <img alt="" className="icon" src="assets/img/linked_in.svg" />
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="col-md-6">
          <div className="footer-section">
            <h5>Navigate</h5>
            <div className="row">
              <div className="col-xs-6">
                <a href="/">About</a><br />
                <a href="/">Profile</a>
              </div>
              <div className="col-xs-6">
                <a href="/">Blog</a><br />
                <a href="/">Contact</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
);

export default Footer;

// src/app/shared/component/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'cag-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.less']
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="footer-section">
                    <h5>Connect</h5>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="http://facebook.com" class="social-media-icon"><img class="icon" src="assets/img/facebook.svg"/></a>
                            <a href="http://twitter.com" class="social-media-icon"><img class="icon" src="assets/img/twitter.svg"/></a>
                            <a href="http://linkedin.com" class="social-media-icon"><img class="icon" src="assets/img/linked_in.svg"/></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="footer-section">
                    <h5>Navigate</h5>
                    <div class="row">
                        <div class="col-xs-6">
                            <a>About</a><br />
                            <a>Profile</a>
                        </div>
                        <div class="col-xs-6">
                            <a>Blog</a><br />
                            <a>Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
