// src/components/header.jsx
import React from 'react';
import PropTypes from 'prop-types';

const Header = ({ exploded }) => (
  <header className={`navbar${exploded ? ' exploded' : ''}`}>
    <div className="container">
      <div className="navbar-header">
        <button type="button" className="navbar-toggle collapsed">
          <span className="sr-only">Toggle navigation</span>
          <span className="icon-bar" />
          <span className="icon-bar" />
          <span className="icon-bar" />
        </button>
        <a className="navbar-brand" href="/">craig a. green</a>
      </div>
      <div className="collapse navbar-collapse">
        <ul className="nav navbar-nav">
          <li><a href="/about">About</a></li>
          <li><a href="/profile">Profile</a></li>
          <li><a href="/blog">Blog</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </header>
);

Header.propTypes = {
  exploded: PropTypes.bool,
};

Header.defaultProps = {
  exploded: false,
};

export default Header;

// src/app/shared/component/header/header.component.ts
import {Component, OnInit, Input, EventEmitter} from '@angular/core';
import {Output} from "@angular/core/src/metadata/directives";

@Component({
  selector: 'cag-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.less']
})
export class HeaderComponent implements OnInit {
    @Input() private headerExploded: boolean;
    @Input() private sidebarCollapsed: boolean;
    @Output() private toggle: EventEmitter<boolean> = new EventEmitter<boolean>();

    constructor() { }

    ngOnInit() {
    }

    collapse() {
        this.toggle.emit(!this.sidebarCollapsed);
    }

}

<header class="navbar {{headerExploded ? 'exploded' : ''}}">
    <div class="container">

        <div class="navbar-header">
            <button (click)="collapse()" type="button" class="navbar-toggle collapsed">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">craig a. green</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a routerLink="/about">About</a></li>
                <li><a routerLink="/profile">Profile</a></li>
                <li><a routerLink="/blog">Blog</a></li>
                <li><a routerLink="/contact">Contact</a></li>
            </ul>
        </div>

    </div>
</header>
